// Copyright 2023-latest Tomoki Miyauchi. All rights reserved. MIT license.
// This module is browser compatible.

export {
  assert,
  type AssertOptions,
  Err,
  type GreedyAssertOptions,
  type LazyAssertOptions,
  Ok,
  type Result,
  validate,
  type ValidateOptions,
  ValidationError,
  type ValidationErrorOptions,
} from "./validation.ts";
export {
  Reporter,
  type ValidationContext,
  ValidationFailure,
  type ValidationFailureOptions,
  type Validator,
} from "./types.ts";
export {
  and,
  between,
  bigint,
  boolean,
  count,
  empty,
  enumerate,
  eq,
  fixedArray,
  float,
  gt,
  gte,
  instance,
  int,
  int16,
  int32,
  int8,
  item,
  key,
  lt,
  lte,
  maxCount,
  minCount,
  ne,
  negative,
  nonEmpty,
  nonNegative,
  nonPositive,
  not,
  nullish,
  number,
  object,
  optional,
  or,
  pattern,
  positive,
  prototype,
  single,
  string,
  symbol,
  type,
  uint16,
  uint32,
  uint8,
  unique,
  validDate,
  value,
} from "./bindings.ts";
export { lazy } from "./utils.ts";
export { type TypeStr, TypeValidator } from "./validators/operators/typeof.ts";
